GameWorld/Components/CartSummaryViewComponent.cs
using GameWorld.Models;
using Microsoft.AspNetCore.Mvc;

namespace GameWorld.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cart)
        {
            this.cart = cart;
        }

        public IViewComponentResult Invoke() => View(cart);
    }
}

GameWorld/Controllers/CartController.cs
using GameWorld.Models;
using GameWorld.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace GameWorld.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;

        public CartController(IProductRepository repository, Cart cart)
        {
            this.repository = repository;
            this.cart = cart;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }


    }
}

GameWorld/Views/Shared/ProductSummary.cshtml
@model Product

@*<div class="well">
        <h3 class="pull-right">
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary">@Model.Price.ToString("C")</span>
        </h3>
        <span class="lead">@Model.Description</span>
    </div>*@

<div class="container">
    <div class="col-xs-3">
        <img src="@Model.ImageUrl" class="img-thumbnail pull-left" />
        <br />
        <br />
        <span class="label label-primary">@Model.Price.ToString("C")</span>
        <form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post">
            <input type="hidden" asp-for="ProductID" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <button type="submit" class="btn btn-sm btn-success pull-right">
                <i class="fa fa-cart-plus"></i>&nbsp;Add to cart
            </button>
        </form>
    </div>
    <br />

    <div class="col-xs-9">
        <h3>
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="@Model.Screenshot1" height="200px;" width="820px;" class="img-responsive center-block">
                    </div>

                    <div class="item">
                        <img src="@Model.Screenshot2" height="200px;" width="820px;" class="img-responsive center-block">
                    </div>

                    <div class="item">
                        <img src="@Model.Screenshot3" height="200px;" width="820px;" class="img-responsive center-block">
                    </div>
                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>


            @*<i class="alert-info text-center"><b>@Model.Description</b></i>*@
            @*<img src="@Model.Screenshot1" height="150px;" width="200px;"/>
                <img src="@Model.Screenshot2" height="150px;" width="200px;"/>
                <img src="@Model.Screenshot3" height="150px;" width="200px;"/>*@

        </h3>
        <br />

    </div>
</div>

GameWorld/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.css" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
            font-weight: bold;
        }
    </style>
    <script asp-src-include="lib/jquery/**/jquery.min.js"></script>
    <script asp-src-include="lib/jquery-validation/**/jquery.validate.min.js"></script>
    <script asp-src-include="lib/jquery-validation-unobtrusive/**/*.min.js"></script>
</head>
<body class="panel panel-primary">
    <div class="panel-heading">
        <h4>@ViewBag.Title</h4>

    </div>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        <br />
        <a class="btn btn-sm btn-default pull-right" asp-action="Logout" asp-controller="Account">
            <i class="fa fa-sign-out text-danger"></i>&nbsp;Log out
        </a>
        @RenderBody()
    </div>
</body>
</html>

GameWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.css" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
    <title>Game World</title>
    <script asp-src-include="lib/jquery/**/jquery.min.js"></script>
    <script asp-src-include="lib/bootstrap/**/*.js"></script>
</head>
<body>
    <div class="navbar navbar-default" role="navigation">
        <a class="navbar-brand" href="#">
            <i class="fa fa-2x fa-futbol-o text-primary"></i>&nbsp;&nbsp;<b class="text-danger">GAME </b><b class="text-success">WORLD</b>
        </a>
        <div class="pull-right">
            @await Component.InvokeAsync("CartSummary")
        </div>
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>

</body>
</html>